### ISSUE TITLE
Fatal error: Class 'SELF' not found

### ISSUE THREAD

**Issue by mathijsm** [GordonLesti/Lesti_Fpc#155]
Hello Gordon,

we are using your FPC, but after the update we get this error 
Fatal error: Class 'SELF' not found in Lesti_Fpc/app/code/community/Lesti/Fpc/Helper/Data.php on line179

if we change the code to "self" the issue is fixed.

we are using php version PHP 5.4.44-1byte1

greets Michel

**Comment by GordonLesti** [comment]
thank you @mathijsm 
should be fixed with https://github.com/GordonLesti/Lesti_Fpc/releases/tag/1.4.1

**Comment by mathijsm** [comment]
hey @GordonLesti ,

you forgot the line 180 their is also a SELF, maybe i should also have mentioned that :-(

thx

**Comment by GordonLesti** [comment]
@mathijsm thank you again, I should have seen it:(
Funny that the feature worked for me, I have `PHP 5.6.13-0+deb8u1`.

**Comment by GordonLesti** [comment]
But it fatally shows that I should write a test for the section.
